import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme";
import ContextRoot from "@/context/app";
import { NavbarWithMegaMenu } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange>
          <ContextRoot>
            <NavbarWithMegaMenu />
            {children}
          </ContextRoot>
        </ThemeProvider>
      </body>
    </html>
  );
}
